# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82619c68a244279a34fa90af8bac272ebf0aaeeac4cd3cc432da41055cb4ea9b06f865a5476b17e6921de732eb1dd4259164c35c40658d453161b4215c11100c

test:
  secret_key_base: 57c96bb0d51ed5f35d5a37306a1a2b81baf0e7a7739fe88240b4c07c7914f7b946ad59d59d56e31b0a8c5e2c8e2283f8af726e086f3730fc11006b8c116aec3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
